apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-ingress
spec:
  tls:
  - hosts:
    - placeholder.com
    secretName: example-tls-secret
  rules:
  - host: placeholder.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: go-proba
            port:
              number: 80
