apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-proba-deployment
  labels:
    app: go-proba
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-proba
  template:
    metadata:
      labels:
        app: go-proba
    spec:
      containers:
      - name: goproba
        image: ghcr.io/corvuscoraxhd/go-proba:latest
        ports:
        - containerPort: 8080
