name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u corvuscoraxhd --password-stdin

      - name: Build and Push Docker image
        run: |
          docker build -t ghcr.io/corvuscoraxhd/go-proba:latest .
          docker push ghcr.io/corvuscoraxhd/go-proba:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GKE_CREDENTIALS }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'
          project_id: go-proba

      - uses: simenandre/setup-gke-gcloud-auth-plugin@v1

      - name: Configure gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin
          gcloud container clusters get-credentials go-proba-cluster --zone us-west1-a --project hypnotic-guard-425421-m8

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f kubernetes/deployment.yaml
          kubectl apply -f kubernetes/service.yaml
          kubectl apply -f kubernetes/ingress.yaml
          kubectl apply -f kubernetes/cert-manager.yaml
