name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/corvuscoraxhd/go-proba:latest .
          docker push ghcr.io/corvuscoraxhd/go-proba:latest
