name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u corvuscoraxhd --password-stdin

      - name: Build and Push Docker image
        run: |
          docker build -t ghcr.io/corvuscoraxhd/go-proba:latest .
          docker push ghcr.io/corvuscoraxhd/go-proba:latest
